language: elixir

notifications:
  email: false

elixir:
  - 1.8.2

otp_release:
  - 21.0

matrix:
  include:
    - elixir: "1.6"
      otp_release: "19.0"
    - elixir: "1.8"
      otp_release: "21.0"
      env:
        - DIALYZER=true
        - CREDO=true

script:
  - mix test
  - if [ "$DIALYZER" ]; then mix dialyzer --halt-exit-status; fi
  - if [ "$CREDO" ]; then mix credo; fi

cache:
  directories:
    - priv/plts
    - _build
    - deps
