os: linux
dist: xenial
language: elixir

elixir:
  - 1.9.4

otp_release:
  - 22

jobs:
  include:
    - elixir: "1.6"
      otp_release: "20"
    - elixir: "1.8"
      otp_release: "21"
    - elixir: "1.9"
      otp_release: "22"
      env:
        - DIALYZER=true
        - CREDO=true
    - elixir: "1.10"
      otp_release: "23"

script:
  - mix test
  - if [ "$DIALYZER" ]; then mix dialyzer --no-compile; fi
  - if [ "$CREDO" ]; then mix credo; fi

cache:
  directories:
    - priv/plts
    - _build
    - deps

notifications:
  email: false
